# Generated by Django 5.2.7 on 2026-04-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="major",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
